config/routes.rb
Rails.application.routes.draw do
  resources :battles

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/battles/_form.html.erb
<%= form_for(@battle) do |f| %>
  <% if @battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% @battle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_field :link, class:"form-control", placeholder:'link de youtube' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_area :content, class:"form-control", rows:'5', placeholder:'Introduce las palabras separadas por comas' %>
    </div>
  </div>
  <div class="actions col-md-6 col-md-offset-3">
    <%= f.submit 'Crear Batalla', :class => 'btn btn-info btn-block'%>
  </div>
<% end %>

app/views/battles/index.html.erb
<p id="notice"><%= notice %></p>




<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default">
    <div class="panel-heading">Listado de batallas</div>
    <table class="table">
      <thead>
        <tr>
          <th>Beat</th>
          <th>Some words</th>
          <th>Options</th>
          
        </tr>
      </thead>
      <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><iframe width="420" height="auto" src=<%='https://www.youtube.com/embed/' + battle.link %> frameborder="0" allowfullscreen></iframe></td>
        <td><%= battle.content.truncate(200) %></td>
        <td><%= link_to 'Show', battle %>, <%= link_to 'Edit', edit_battle_path(battle) %>, <%= link_to 'Destroy', battle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
    </table>
  </div>
  

<br>

app/views/battles/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Battle</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', battles_path %>

app/views/battles/show.html.erb
<p id="notice"><%= notice %></p> 
  <div class="col-md-6 col-md-offset-3" id='wrapper'>
 	<h1 id="word">tu palabra</h1>
 	<h2 id="counter" >0</h2>
     <div id="play" class="button tubular-play"><span><i class="glyphicon glyphicon-play"></i></span></div>
     <div id="play" class="button tubular-pause"><span><i class="glyphicon glyphicon-pause"></i></span></div>
 	 <div id="change-text" class="button"><span>Change Text</span></div>
 	 <div id="bonus" class="button"><span><i class="glyphicon glyphicon-star"></i> Bonus <i class="glyphicon glyphicon-star"></i></span></div>
 	

 </div>





  
  




<div class="col-md-12">
<p>
  <strong>Content:</strong>
  <p id="content"><%= @battle.content %></p>
</p>

<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>
</div>
<script>
	$("document").ready(function() {
  var options = {  videoId: "<%= @battle.link %>", 
                   start: 0, 
                   repeat: true,
                   mute: false,
                   playButtonClass: 'tubular-play',
                   pauseButtonClass: 'tubular-pause',

                };  
  
	$('#wrapper').tubular(options); 
}); 
</script>




<script>



				var split = document.getElementById('content').innerHTML.split(',');


				var nvalue = 0;
				var score = 0;
				$("#change-text").on("click", function() {

						document.getElementById('counter').innerHTML = score++;
						
						var word = split[nvalue++];
						document.getElementById('word').innerHTML = word;
						
				});
				$("#bonus").on("click", function() {
						var plusscore = score + 5;
						document.getElementById('counter').innerHTML = plusscore;
						score = plusscore;
						
						
				});


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rhymes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
    <nav style="z-index:999" class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "RhymeThis", root_path %></li>
            <li><%= link_to "Battles", battles_path %></li>
            <li><%= link_to 'New Battle', new_battle_path %></li>
            <!-- <li class="disabled"><a href="#">Link</a></li> -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Setting</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="active"><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li class="disabled"><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-search search-only">
              <i class="search-icon glyphicon glyphicon-search"></i>
              <input type="text" class="form-control search-query">
            </div>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  






<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="col-md-6 col-md-offset-3">
            <div class="jumbotron">
              <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="item active"><img src="http://i.ytimg.com/vi/Tlr-uXmC35c/maxresdefault.jpg"></div>
                  <div class="item"><img src="http://i.ytimg.com/vi/nWgZWkZcRZ4/maxresdefault.jpg"></div>
                  <div class="item"><img src="http://i.ytimg.com/vi/k5CRCWTzlwA/maxresdefault.jpg"></div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
              <div class="jumbotron-contents">
                <h1>Rhymethis App</h1>
                <h2>Do you want to practice your freestyle habilities? This is your place!</h2>
                <p>More than 300 battles readdy to beat for you. Beat and words together in the same time in orther to make your freestyle tasks easiers.</p>
                <h2>All styles of music</h2>
                <p>More than 300 battles readdy to beat for you. Beat and words together in the same time in orther to make your freestyle tasks easiers.</p>
              </div>
            </div>
          </div>
        </div>
      </div>